---
# tasks file for cron
- name: check for anacrontab.
  stat:
    path: /usr/sbin/anacron
  register: aspects_cron_register_anacron
  tags:
    - aspects_cron
    - aspects_cron_debug

- name: Set crontab template
  when: not aspects_cron_register_anacron.stat.exists
  template:
    src: "crontab.j2"
    dest: "/etc/crontab"
  tags:
    - aspects_cron
    - aspects_cron_crontab

- name: Set anacrontab template
  when: aspects_cron_register_anacron.stat.exists
  template:
    src: "anacrontab.j2"
    dest: "/etc/anacrontab"
  tags:
    - aspects_cron
    - aspects_cron_anacrontab

- name: Set normal cronjobs
  when: item.value.special_time is not defined
  become: True
  cron:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    backup: "{{ item.value.backup }}"
    minute: "{{ item.value.minute }}"
    hour: "{{ item.value.hour }}"
    day: "{{ item.value.day }}"
    weekday: "{{ item.value.weekday }}"
    month: "{{ item.value.month }}"
    user: "{{ item.value.user }}"
    job: "{{ item.value.job }}"
  with_dict: "{{ aspects_cron_jobs|default('{}') }}"
  tags:
    - aspects_cron

- name: Set special cronjobs
  when: item.value.special_time is defined
  cron:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    backup: "{{ item.value.backup }}"
    special_time: "{{ item.value.special_time }}"
    user: "{{ item.value.user }}"
    job: "{{ item.value.job }}"
  with_dict: "{{ aspects_cron_jobs|default('{}') }}"
  tags:
    - aspects_cron
