---
# tasks file for cron
- name: check for anacrontab.
  stat:
    path: /usr/sbin/anacron
  register: aspects_cron_register_anacron
  tags:
    - aspects_cron
    - aspects_cron_debug

- name: Set crontab template
  when: not aspects_cron_register_anacron.stat.exists
  template:
    src: "crontab.j2"
    dest: "/etc/crontab"
  tags:
    - aspects_cron
    - aspects_cron_crontab

- name: Set anacrontab template
  when: aspects_cron_register_anacron.stat.exists
  template:
    src: "anacrontab.j2"
    dest: "/etc/anacrontab"
  tags:
    - aspects_cron
    - aspects_cron_anacrontab

- name: Set normal cronjobs
  when: item.1.special_time is not defined
  become: True
  cron:
    name: "{{ item.1.name }}"
    state: "{{ item.1.state }}"
    backup: "{{ item.1.backup }}"
    minute: "{{ item.1.minute }}"
    hour: "{{ item.1.hour }}"
    day: "{{ item.1.day }}"
    weekday: "{{ item.1.weekday }}"
    month: "{{ item.1.month }}"
    user: "{{ item.1.user }}"
    job: "{{ item.1.job }}"
  loop: "{{ aspects_cron_jobs|default({}) | dictsort }}"
  tags:
    - aspects_cron

- name: Set special cronjobs
  when: item.1.special_time is defined
  cron:
    name: "{{ item.1.name }}"
    state: "{{ item.1.state }}"
    backup: "{{ item.1.backup }}"
    special_time: "{{ item.1.special_time }}"
    user: "{{ item.1.user }}"
    job: "{{ item.1.job }}"
  loop: "{{ aspects_cron_jobs|default({}) | dictsort }}"
  tags:
    - aspects_cron

- name: Manage env for a users crontab
  when:
    - aspects_cron_job_env is defined
    - item.1.enabled
  cron:
    name: "{{ item.1.variable }}"
    env: yes
    job: "{{ item.1.value }}"
    user: "{{ item.1.user }}"
  loop: "{{ aspects_cron_job_env | default({}) | dictsort }}"
  tags:
    - aspects_cron